name: lint

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: Branch to run the linting on.

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --depth=1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ubuntu-latest-${{ hashFiles('**/yarn.lock') }}
      - name: Run lint:fix
        run: |
          yarn install --frozen-lockfile
          git checkout ${{ github.event.inputs.branch }}
          git pull
          yarn lint:fix
      - name: Commit Changes if needed
        env:
          USE_SSH: true
          GIT_USER: cloud-sdk-js
        run : |
          git config --global user.email "cloud-sdk-js@github.com"
          git config --global user.name "cloud-sdk-js"
          diff=`git diff`
          if [ ! -z "$diff" ]; then
            git commit -m "Changes from lint:fix" -a
            git push -u origin ${{ github.event.inputs.branch }}
          fi
